import Sidebar from '@/components/sidebar/Sidebar'
import GlobalProviders from '@/contexts/global-providers'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<GlobalProviders>
					<Sidebar />
					<main className='bg-gray-100 pl-24'>{children}</main>
				</GlobalProviders>
			</body>
		</html>
	)
}
